Importing the dependencies:

In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

Data Collection and analysis:
student dippression dataset..

In [3]:
#loading the dataset to a pandas DataFrame
Sdepression_datadet= pd.read_csv('/content/Student Depression Dataset.csv')

# New Section

In [4]:
pd.read_csv?

In [5]:
#printing the first five rows of the dataset
Sdepression_datadet.head()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0

In [6]:
# number of rows and Columns in this dataset
Sdepression_datadet.shape

(27901, 18)

In [7]:
# getting the statistical measures of the data
Sdepression_datadet.describe()

,id,Age,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Work/Study Hours,Financial Stress,Depression
count,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27898.000000,27901.000000
mean,70442.149421,25.822300,3.141214,0.000430,7.656104,2.943837,0.000681,7.156984,3.139867,0.585499
std,40641.175216,4.905687,1.381465,0.043992,1.470707,1.361148,0.044394,3.707642,1.437347,0.492645
min,2.000000,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,35039.000000,21.000000,2.000000,0.000000,6.290000,2.000000,0.000000,4.000000,2.000000,0.000000
50%,70684.000000,25.000000,3.000000,0.000000,7.770000,3.000000,0.000000,8.000000,3.000000,1.000000
75%,105818.000000,30.000000,4.000000,0.000000,8.920000,4.000000,0.000000,10.000000,4.000000,1.000000
max,140699.000000,59.000000,5.000000,5.000000,10.000000,5.000000,4.000000,12.000000,5.000000,1.000000

In [8]:
Sdepression_datadet['Depression'].value_counts()

Depression
1    16336
0    11565
Name: count, dtype: int64

0--->not depressed
1---> depressed

In [9]:
# Get a list of numerical columns
numerical_cols = Sdepression_datadet.select_dtypes(include=np.number).columns

# Calculate the mean for numerical columns only
Sdepression_datadet.groupby('Depression')[numerical_cols].mean()

,id,Age,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Work/Study Hours,Financial Stress,Depression
Depression,,,,,,,,,,
0,70397.561089,27.142412,2.361608,0.000605,7.617282,3.215564,0.000865,6.237959,2.518724,0.0
1,70473.715536,24.887733,3.693132,0.000306,7.683588,2.751469,0.000551,7.807603,3.579553,1.0

In [10]:
# separating the data and labels
X = Sdepression_datadet.drop(columns = 'Depression', axis=1)
Y = Sdepression_datadet['Depression']

In [11]:
print(X)

           id  Gender   Age           City Profession  Academic Pressure  \
0           2    Male  33.0  Visakhapatnam    Student                5.0
1           8  Female  24.0      Bangalore    Student                2.0
2          26    Male  31.0       Srinagar    Student                3.0
3          30  Female  28.0       Varanasi    Student                3.0
4          32  Female  25.0         Jaipur    Student                4.0
...       ...     ...   ...            ...        ...                ...
27896  140685  Female  27.0          Surat    Student                5.0
27897  140686    Male  27.0       Ludhiana    Student                2.0
27898  140689    Male  31.0      Faridabad    Student                3.0
27899  140690  Female  18.0       Ludhiana    Student                5.0
27900  140699    Male  27.0          Patna    Student                4.0

       Work Pressure  CGPA  Study Satisfaction  Job Satisfaction  \
0                0.0  8.97                 2.0               0.0
1                0.0  5.90                 5.0               0.0
2                0.0  7.03                 5.0               0.0
3                0.0  5.59                 2.0               0.0
4                0.0  8.13                 3.0               0.0
...              ...   ...                 ...               ...
27896            0.0  5.75                 5.0               0.0
27897            0.0  9.40                 3.0               0.0
27898            0.0  6.61                 4.0               0.0
27899            0.0  6.88                 2.0               0.0
27900            0.0  9.24                 1.0               0.0

          Sleep Duration Dietary Habits    Degree  \
0              5-6 hours        Healthy   B.Pharm
1              5-6 hours       Moderate       BSc
2      Less than 5 hours        Healthy        BA
3              7-8 hours       Moderate       BCA
4              5-6 hours       Moderate    M.Tech
...                  ...            ...       ...
27896          5-6 hours      Unhealthy  Class 12
27897  Less than 5 hours        Healthy       MSc
27898          5-6 hours      Unhealthy        MD
27899  Less than 5 hours        Healthy  Class 12
27900  Less than 5 hours        Healthy       BCA

      Have you ever had suicidal thoughts ?  Work/Study Hours  \
0                                       Yes               3.0
1                                        No               3.0
2                                        No               9.0
3                                       Yes               4.0
4                                       Yes               1.0
...                                     ...               ...
27896                                   Yes               7.0
27897                                    No               0.0
27898                                    No              12.0
27899                                   Yes              10.0
27900                                   Yes               2.0

       Financial Stress Family History of Mental Illness
0                   1.0                               No
1                   2.0                              Yes
2                   1.0                              Yes
3                   5.0                              Yes
4                   1.0                               No
...                 ...                              ...
27896               1.0                              Yes
27897               3.0                              Yes
27898               2.0                               No
27899               5.0                               No
27900               3.0                              Yes

[27901 rows x 17 columns]

In [12]:
print(Y)

0        1
1        0
2        0
3        1
4        0
        ..
27896    0
27897    0
27898    0
27899    1
27900    1
Name: Depression, Length: 27901, dtype: int64

In [13]:
# Step 2: Identify categorical columns
categorical_cols = X.select_dtypes(include='object').columns

In [14]:
# Step 3: Convert categorical columns using one-hot encoding (or use LabelEncoding for binary)
X_encoded = pd.get_dummies(X, columns=categorical_cols, drop_first=True)

Data Standardization:

In [15]:
# Impute missing values (only for numerical columns)

imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X_encoded)  # Impute missing values in the entire datase

In [16]:
# 4. Scale the imputed data (Standardize the features)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_imputed)  # Scale after imputation

In [17]:
# 5. Convert back to DataFrame for readability
X_scaled_df = pd.DataFrame(X_scaled, columns=X_encoded.columns)

In [18]:
print(X_scaled_df.head())  # Check the first few rows of the scaled data

         id       Age  Academic Pressure  Work Pressure      CGPA  \
0 -1.733252  1.463165           1.345543      -0.009777  0.893393
1 -1.733105 -0.371474          -0.826104      -0.009777 -1.194076
2 -1.732662  1.055467          -0.102222      -0.009777 -0.425724
3 -1.732563  0.443921          -0.102222      -0.009777 -1.404862
4 -1.732514 -0.167625           0.621660      -0.009777  0.322229

   Study Satisfaction  Job Satisfaction  Work/Study Hours  Financial Stress  \
0           -0.693425          -0.01534         -1.121213         -1.488868
1            1.510636          -0.01534         -1.121213         -0.793092
2            1.510636          -0.01534          0.497095         -1.488868
3           -0.693425          -0.01534         -0.851495          1.294237
4            0.041262          -0.01534         -1.660650         -1.488868

   Gender_Male  ...  Degree_MBBS  Degree_MCA  Degree_MD  Degree_ME  \
0     0.891416  ...    -0.159949   -0.197161  -0.144673    -0.0817
1    -1.121811  ...    -0.159949   -0.197161  -0.144673    -0.0817
2     0.891416  ...    -0.159949   -0.197161  -0.144673    -0.0817
3    -1.121811  ...    -0.159949   -0.197161  -0.144673    -0.0817
4    -1.121811  ...    -0.159949   -0.197161  -0.144673    -0.0817

   Degree_MHM  Degree_MSc  Degree_Others  Degree_PhD  \
0   -0.083023   -0.211071       -0.03544   -0.138079
1   -0.083023   -0.211071       -0.03544   -0.138079
2   -0.083023   -0.211071       -0.03544   -0.138079
3   -0.083023   -0.211071       -0.03544   -0.138079
4   -0.083023   -0.211071       -0.03544   -0.138079

   Have you ever had suicidal thoughts ?_Yes  \
0                                   0.761745
1                                  -1.312775
2                                  -1.312775
3                                   0.761745
4                                   0.761745

   Family History of Mental Illness_Yes
0                             -0.968421
1                              1.032609
2                              1.032609
3                              1.032609
4                             -0.968421

[5 rows x 110 columns]

In [19]:
print(Y.head())

0    1
1    0
2    0
3    1
4    0
Name: Depression, dtype: int64

Splitting the data to training data and test data:

In [20]:
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled_df, Y, test_size=0.2, stratify=Y, random_state=2)

In [21]:
# checking if the split for test and train:
print("Train label distribution:\n", Y_train.value_counts(normalize=True))

Train label distribution:
 Depression
1    0.585484
0    0.414516
Name: proportion, dtype: float64

In [22]:
print("Test label distribution:\n", Y_test.value_counts(normalize=True))

Test label distribution:
 Depression
1    0.585558
0    0.414442
Name: proportion, dtype: float64

In [23]:
print(X.shape, X_train.shape, X_test.shape)

(27901, 17) (22320, 110) (5581, 110)

Data Standardization:

In [24]:
print(X_train)

             id       Age  Academic Pressure  Work Pressure      CGPA  \
22753  1.088936 -1.390717          -0.826104      -0.009777  1.042983
23846  1.222350 -1.390717          -1.549987      -0.009777 -1.357265
16844  0.363575  0.647770          -0.826104      -0.009777 -0.187739
483   -1.672500  0.443921           0.621660      -0.009777  1.403361
13117 -0.098674  0.240073          -0.826104      -0.009777 -0.575315
...         ...       ...                ...            ...       ...
15074  0.136781  0.443921          -0.102222      -0.009777 -1.500056
1331  -1.564455  0.240073          -0.102222      -0.009777  0.845796
24610  1.318092 -1.390717           1.345543      -0.009777  0.261033
10309 -0.448449 -0.167625           1.345543      -0.009777  0.553414
25157  1.385759  1.055467           1.345543      -0.009777 -1.207675

       Study Satisfaction  Job Satisfaction  Work/Study Hours  \
22753           -1.428112          -0.01534          0.227377
23846           -1.428112          -0.01534         -0.312059
16844            0.775949          -0.01534         -1.930368
483             -1.428112          -0.01534          1.306249
13117           -1.428112          -0.01534          0.497095
...                   ...               ...               ...
15074            0.041262          -0.01534         -0.312059
1331             0.775949          -0.01534          0.766813
24610           -1.428112          -0.01534         -1.390931
10309           -0.693425          -0.01534         -0.581777
25157           -0.693425          -0.01534          1.306249

       Financial Stress  Gender_Male  ...  Degree_MBBS  Degree_MCA  Degree_MD  \
22753          1.294237    -1.121811  ...    -0.159949   -0.197161  -0.144673
23846          0.598460     0.891416  ...    -0.159949   -0.197161  -0.144673
16844         -1.488868    -1.121811  ...    -0.159949   -0.197161  -0.144673
483           -0.097316    -1.121811  ...    -0.159949   -0.197161  -0.144673
13117         -1.488868    -1.121811  ...    -0.159949   -0.197161  -0.144673
...                 ...          ...  ...          ...         ...        ...
15074         -0.097316     0.891416  ...    -0.159949   -0.197161  -0.144673
1331           0.598460     0.891416  ...    -0.159949   -0.197161  -0.144673
24610         -1.488868    -1.121811  ...    -0.159949   -0.197161  -0.144673
10309         -0.793092     0.891416  ...    -0.159949   -0.197161  -0.144673
25157         -1.488868     0.891416  ...    -0.159949   -0.197161  -0.144673

       Degree_ME  Degree_MHM  Degree_MSc  Degree_Others  Degree_PhD  \
22753    -0.0817   -0.083023   -0.211071       -0.03544   -0.138079
23846    -0.0817   -0.083023   -0.211071       -0.03544   -0.138079
16844    -0.0817   -0.083023   -0.211071       -0.03544   -0.138079
483      -0.0817   -0.083023   -0.211071       -0.03544   -0.138079
13117    -0.0817   -0.083023   -0.211071       -0.03544   -0.138079
...          ...         ...         ...            ...         ...
15074    -0.0817   12.044855   -0.211071       -0.03544   -0.138079
1331     -0.0817   12.044855   -0.211071       -0.03544   -0.138079
24610    -0.0817   -0.083023   -0.211071       -0.03544   -0.138079
10309    -0.0817   -0.083023   -0.211071       -0.03544   -0.138079
25157    -0.0817   -0.083023   -0.211071       -0.03544   -0.138079

       Have you ever had suicidal thoughts ?_Yes  \
22753                                   0.761745
23846                                   0.761745
16844                                  -1.312775
483                                     0.761745
13117                                  -1.312775
...                                          ...
15074                                   0.761745
1331                                   -1.312775
24610                                   0.761745
10309                                  -1.312775
25157                                   0.761745

       Family History of Mental Illness_Yes
22753                             -0.968421
23846                             -0.968421
16844                             -0.968421
483                               -0.968421
13117                              1.032609
...                                     ...
15074                             -0.968421
1331                              -0.968421
24610                             -0.968421
10309                             -0.968421
25157                             -0.968421

[22320 rows x 110 columns]

Model training:

Support vector Machine:

In [25]:
model = svm.SVC(kernel='linear')

In [26]:
print(X_train.isna().sum().sort_values(ascending=False).head(10))  # to check if have any missing values(nan)

id                    0
Age                   0
Academic Pressure     0
Work Pressure         0
CGPA                  0
Study Satisfaction    0
Job Satisfaction      0
Work/Study Hours      0
Financial Stress      0
Gender_Male           0
dtype: int64

In [27]:
#Training the svm model with training data
model.fit(X_train, Y_train)

SVC(kernel='linear')

Model Evaluation:
Acurracy Score:

In [28]:
# accuracy Score on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [29]:
print("Accuracy score of training data:", training_data_accuracy )

Accuracy score of training data: 0.8508064516129032

In [30]:
X_test_pred = model.predict(X_test)
test_acc = accuracy_score(Y_test, X_test_pred)
print("Accuracy score on test data:", test_acc)

Accuracy score on test data: 0.8414262676939617

Building a predictive system:

In [31]:
# Your raw input data (make sure it's in the same order as the original DataFrame)
input_data = (62,'Male',31.0,'Nashik','Student',2.0,0.0,8.38,3.0,0.0,'Less than 5 hours','Moderate','LLB','Yes',2.0,5.0,'No')

# Convert to DataFrame (column names must match original dataset!)
input_df = pd.DataFrame([input_data], columns=[
    'id', 'Gender', 'Age', 'City', 'Profession', 'Academic Pressure', 'Work Pressure',
    'CGPA', 'Study Satisfaction', 'Job Satisfaction', 'Sleep Duration', 'Dietary Habits',
    'Degree', 'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
    'Financial Stress', 'Family History of Mental Illness'
])

# Encode the categorical variables (use same one-hot encoding logic)
input_encoded = pd.get_dummies(input_df)

# Match the input to the training data's columns (fill missing dummy columns with 0)
input_encoded = input_encoded.reindex(columns=X_encoded.columns, fill_value=0)

# Impute missing values (optional if none are expected)
input_imputed = imputer.transform(input_encoded)

# Scale using the previously fitted scaler
input_scaled = scaler.transform(input_imputed)

# Make prediction
prediction = model.predict(input_scaled)
print("Prediction:", prediction)

if (prediction[0]==0):
  print("The person is not depressed")
else:
  print("The person is depressed")

Prediction: [1]
The person is depressed

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

saving the trained model:

In [32]:
import pickle

In [33]:
#saving the trained file

file_name = 'tarined_depression_model.sav'
pickle.dump(model , open(file_name, 'wb'))



# Save the column names from pd.get_dummies (this is your encoder logic)
model_columns = X_encoded.columns.tolist()
with open('encoder_columns.sav', 'wb') as cols_file:
    pickle.dump(model_columns, cols_file)